# Generated by Django 4.2.30 on 2026-06-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_resume_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Stable identifier used by templates, for example about or contact.', max_length=80, unique=True)),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('subtitle', models.TextField(blank=True)),
                ('primary_label', models.CharField(blank=True, max_length=80)),
                ('secondary_label', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
    ]
