# Generated by Django 4.2.30 on 2026-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_seed_page_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(help_text='Use a path or anchor, for example /blog/ or /#contact.', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('opens_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
